/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "pages/index" |
       "pages/hi" |
       "pages/login" |
       "pages/webview" |
       "pages/areaManage/index" |
       "pages/interestedTarget/interestedTargetUnit" |
       "pages/interestedTarget/relPersonAdd" |
       "pages/interestedTarget/relPersonApproval" |
       "pages/interestedTarget/relUnitAdd" |
       "pages/interestedTarget/relUnitApproval" |
       "pages/interestedTarget/vertify" |
       "pages/riskJob/index" |
       "pages/riskJob/shareSignature" |
       "pages-sub/index";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
